import type { RouteRecordRaw } from 'vue-router'

const adminRoutes: RouteRecordRaw = {
  path: '/admin',
  component: () => import('@/layouts/AdminLayout.vue'),
  redirect: '/admin/overview',
  meta: { requiresAuth: true },
  children: [
    {
      path: 'overview',
      name: 'Overview',
      component: () => import('@/views/admin/workbench/WorkbenchRedirect.vue'),
      meta: { title: '工作台' },
    },
    {
      path: 'no-workbench',
      name: 'NoWorkbenchAccess',
      component: () => import('@/views/admin/workbench/NoWorkbenchAccess.vue'),
      meta: { title: '暂无工作台' },
    },
    {
      path: 'workbench/operator',
      name: 'OperatorWorkbench',
      component: () => import('@/views/admin/workbench/OperatorWorkbench.vue'),
      meta: { title: '运营工作台', icon: 'Odometer', permissions: ['workbench.operator.read'] },
    },
    {
      path: 'workbench/sales',
      name: 'SalesWorkbench',
      component: () => import('@/views/admin/workbench/SalesWorkbench.vue'),
      meta: { title: '销售工作台', icon: 'TrendCharts', permissions: ['workbench.sales.read'] },
    },
    {
      path: 'workbench/delivery',
      name: 'DeliveryWorkbench',
      component: () => import('@/views/admin/delivery/DeliveryDashboard.vue'),
      meta: { title: '交付工作台', icon: 'DataAnalysis', permissions: ['delivery.overview.read'] },
    },
    {
      path: 'workbench/manager',
      name: 'ManagerWorkbench',
      component: () => import('@/views/admin/workbench/ManagerWorkbench.vue'),
      meta: { title: '系统工作台', icon: 'Setting', permissions: ['workbench.manager.read'] },
    },
    {
      path: 'workbench/super-admin',
      name: 'SuperAdminWorkbench',
      component: () => import('@/views/admin/workbench/SuperAdminWorkbench.vue'),
      meta: { title: '全局总控', icon: 'DataBoard', roles: ['super_admin'] },
    },
    {
      path: 'profile',
      name: 'AdminProfile',
      component: () => import('@/views/profile/ProfileCenter.vue'),
      meta: { title: '个人中心', hidden: true, requiresAuth: true },
    },
    {
      path: 'customers',
      name: 'CustomerList',
      component: () => import('@/views/admin/customer/CustomerList.vue'),
      meta: { title: '客户管理', icon: 'User', permissions: ['company.read'] },
    },
    {
      path: 'customers/:id',
      name: 'CustomerDetail',
      component: () => import('@/views/admin/customer/CustomerDetail.vue'),
      meta: { title: '客户详情', hidden: true, permissions: ['company.read'] },
    },
    {
      path: 'brands/create',
      name: 'BrandCreate',
      component: () => import('@/views/admin/brand/BrandCreate.vue'),
      meta: { title: '新建品牌', hidden: true, permissions: ['brand.create'] },
    },
    {
      path: 'brands/:id',
      name: 'BrandDetail',
      component: () => import('@/views/admin/brand/BrandDetail.vue'),
      meta: { title: '品牌详情', hidden: true, permissions: ['company.read'] },
    },
    {
      path: 'brands/:id/profile',
      name: 'BrandProfile',
      component: () => import('@/views/admin/brand/BrandProfile.vue'),
      meta: { title: '品牌画像', hidden: true, permissions: ['company.read'] },
    },
    {
      path: 'brands/:id/assets',
      name: 'BrandAssets',
      component: () => import('@/views/admin/brand/BrandAssets.vue'),
      meta: { title: '品牌资产', hidden: true, permissions: ['company.read'] },
    },
    {
      path: 'projects',
      name: 'ProjectList',
      component: () => import('@/views/admin/project/ProjectList.vue'),
      meta: { title: '项目管理', icon: 'Folder', permissions: ['project.read'] },
    },
    {
      path: 'partner-start-requests',
      name: 'PartnerStartRequestWorkbench',
      component: () => import('@/views/admin/partner/PartnerStartRequestWorkbench.vue'),
      meta: { title: '合伙人启动工单', icon: 'Tickets', permissions: ['delivery.assignment.manage'] },
    },
    {
      path: 'partner-start-requests/customers/:id',
      name: 'PartnerSubmittedCustomerDetail',
      component: () => import('@/views/partner/PartnerCustomerDetail.vue'),
      meta: { title: '合伙人客户详情', hidden: true, permissions: ['delivery.assignment.manage', 'company.read'] },
    },
    {
      path: 'partner-start-requests/projects/:id',
      name: 'PartnerSubmittedProjectDetail',
      component: () => import('@/views/partner/PartnerProjectDetail.vue'),
      meta: { title: '合伙人项目详情', hidden: true, permissions: ['delivery.assignment.manage', 'project.read'] },
    },
    {
      path: 'partner-start-requests/brands/:id',
      name: 'PartnerSubmittedBrandDetail',
      component: () => import('@/views/partner/PartnerBrandDetail.vue'),
      meta: { title: '合伙人品牌详情', hidden: true, permissions: ['delivery.assignment.manage', 'company.read'] },
    },
    {
      path: 'projects/:id',
      name: 'ProjectDetail',
      component: () => import('@/views/admin/project/ProjectDetail.vue'),
      meta: { title: '项目详情', hidden: true, permissions: ['project.read'] },
    },
    {
      path: 'projects/:id/tasks',
      name: 'TaskList',
      component: () => import('@/views/admin/project/TaskList.vue'),
      meta: { title: '监测任务', hidden: true, roles: ['operator', 'delivery_manager', 'manager', 'super_admin'] },
    },
    {
      path: 'projects/:id/reports',
      name: 'ProjectReports',
      component: () => import('@/views/admin/project/ReportList.vue'),
      meta: { title: '项目报表', hidden: true, permissions: ['project.read'] },
    },
    {
      path: 'projects/:id/baseline-report',
      name: 'ProjectBaselineReport',
      component: () => import('@/views/admin/project/BaselineReportPoll.vue'),
      meta: { title: '基线检测报告', hidden: true, permissions: ['project.read'] },
    },
    {
      path: 'projects/:id/mobile-dashboard',
      name: 'ProjectMobileDashboardAdmin',
      component: () => import('@/views/admin/project/MobileDashboardAdmin.vue'),
      meta: { title: '移动数据看板', hidden: true, permissions: ['project.read'] },
    },
    {
      path: 'projects/:id/review',
      name: 'ReviewPanel',
      component: () => import('@/views/admin/project/ReviewPanel.vue'),
      meta: { title: '达标评估', hidden: true, permissions: ['project.read'] },
    },
    {
      path: 'monitoring',
      redirect: '/admin/monitoring/tasks',
      meta: { hidden: true },
    },
    {
      path: 'delivery/dashboard',
      name: 'DeliveryDashboard',
      component: () => import('@/views/admin/delivery/DeliveryDashboard.vue'),
      meta: { title: '交付看板', hidden: true, permissions: ['delivery.overview.read'] },
    },
    {
      path: 'monitoring/tasks',
      name: 'MonitoringTasks',
      component: () => import('@/views/admin/monitoring/MonitoringDashboard.vue'),
      meta: { title: '调度监控', icon: 'Monitor', permissions: ['content.distribution.retry', 'dispatch.alert.resolve', 'dispatch.task.replay.dead_letter'] },
    },
    {
      path: 'monitoring/self-media-automation',
      name: 'SelfMediaAutomationOverview',
      component: () => import('@/views/admin/content/SelfMediaAutomationOverview.vue'),
      meta: { title: '自媒体自动化态势', icon: 'DataLine', permissions: ['content.read'] },
    },
    {
      path: 'monitoring/self-media-runtime',
      name: 'SelfMediaRuntimeEnvironment',
      component: () => import('@/views/admin/content/SelfMediaRuntimeEnvironment.vue'),
      meta: { title: '自媒体运行环境', icon: 'Monitor', permissions: ['content.read'] },
    },
    {
      path: 'monitoring/account-auth-health',
      name: 'AccountAuthHealth',
      component: () => import('@/views/admin/content/AccountAuthHealth.vue'),
      meta: { title: '账号授权健康', icon: 'Warning', permissions: ['content.read'] },
    },
    {
      path: 'content/execution',
      name: 'ContentExecution',
      component: () => import('@/views/admin/content/ContentExecution.vue'),
      meta: { title: '内容与执行', icon: 'Memo', permissions: ['content.read'] },
    },
    {
      path: 'content/special-industry-compliance',
      name: 'SpecialIndustryComplianceWorkbench',
      component: () => import('@/views/admin/content/SpecialIndustryComplianceWorkbench.vue'),
      meta: { title: '行业专项工作台', icon: 'Files', permissions: ['content.read'] },
    },
    {
      path: 'content/articles/manual-create',
      name: 'ManualArticleCreate',
      component: () => import('@/views/admin/content/ManualArticleCreate.vue'),
      meta: { title: '导入文章', hidden: true, permissions: ['content.article.write'] },
    },
    {
      path: 'content/articles/ai-create',
      name: 'AiArticleCreate',
      component: () => import('@/views/admin/content/AiArticleCreate.vue'),
      meta: { title: 'AI 单篇生成', hidden: true, permissions: ['content.ai.generate'] },
    },
    {
      path: 'content/articles/batch-generate',
      name: 'BatchArticleGenerate',
      component: () => import('@/views/admin/content/BatchArticleGenerate.vue'),
      meta: { title: '批量生成文章', hidden: true, permissions: ['content.ai.generate'] },
    },
    {
      path: 'content/article-prompt-templates',
      name: 'ArticlePromptTemplates',
      component: () => import('@/views/admin/content/ArticlePromptTemplates.vue'),
      meta: { title: '文章提示词模板', hidden: true, permissions: ['content.prompt_template.manage', 'delivery.assignment.manage'] },
    },
    {
      path: 'content/special-industry-config',
      name: 'SpecialIndustryConfig',
      component: () => import('@/views/admin/content/SpecialIndustryConfig.vue'),
      meta: { title: '特殊行业文章配置', hidden: true, permissions: ['content.prompt_template.manage'] },
    },
    {
      path: 'content/medical-article-config',
      name: 'MedicalArticleConfig',
      redirect: '/admin/content/special-industry-config',
      meta: { title: '特殊行业文章配置', hidden: true, permissions: ['content.prompt_template.manage'] },
    },
    {
      path: 'content/wechat-templates',
      name: 'WechatRenderTemplates',
      component: () => import('@/views/admin/content/wechat-template/TemplateList.vue'),
      meta: { title: '公众号样式模板', hidden: true, permissions: ['content.wechat_template.manage'] },
    },
    {
      path: 'content/wechat-templates/import',
      name: 'WechatRenderTemplateImport',
      component: () => import('@/views/admin/content/wechat-template/TemplateImport.vue'),
      meta: { title: '导入公众号模板', hidden: true, permissions: ['content.wechat_template.manage'] },
    },
    {
      path: 'content/wechat-templates/:templateId/edit',
      name: 'WechatRenderTemplateEdit',
      component: () => import('@/views/admin/content/wechat-template/TemplateImport.vue'),
      meta: { title: '编辑公众号模板', hidden: true, permissions: ['content.wechat_template.manage'] },
    },
    {
      path: 'content/articles/:articleId/wechat-render',
      name: 'WechatArticleRender',
      component: () => import('@/views/admin/content/wechat-render/WechatRenderPage.vue'),
      meta: { title: '公众号渲染', hidden: true, permissions: ['content.read'] },
    },
    {
      path: 'content/articles/batch-publish',
      name: 'BatchArticlePublish',
      component: () => import('@/views/admin/content/BatchArticlePublish.vue'),
      meta: { title: '批量发布文章', hidden: true, permissions: ['content.publish.operate'] },
    },
    {
      path: 'content/articles/batch-publish-jobs',
      name: 'BatchArticlePublishJobs',
      component: () => import('@/views/admin/content/BatchArticlePublishJobs.vue'),
      meta: { title: '批量任务中心', hidden: true, permissions: ['content.read'] },
    },
    {
      path: 'content/publish-platforms',
      name: 'PublishPlatformManagement',
      component: () => import('@/views/admin/content/PublishPlatformManagement.vue'),
      meta: { title: '发布平台管理', hidden: true, permissions: ['user.manage'] },
    },
    {
      path: 'content/self-media-schedule-capabilities',
      name: 'SelfMediaScheduleCapabilityManagement',
      component: () => import('@/views/admin/content/SelfMediaScheduleCapabilityManagement.vue'),
      meta: { title: '自媒体排期能力', hidden: true, permissions: ['user.manage'] },
    },
    {
      path: 'content/publish-platforms/:code',
      name: 'PublishPlatformDetail',
      component: () => import('@/views/admin/content/PublishPlatformDetail.vue'),
      meta: { title: '发布平台详情', hidden: true, permissions: ['user.manage'] },
    },
    {
      path: 'keyword-groups',
      name: 'KeywordGroupManage',
      redirect: '/admin/layered-keyword-groups',
      meta: {
        title: '拓词管理',
        hidden: true,
        roles: ['operator', 'delivery_manager', 'manager', 'super_admin'],
        permissions: ['keyword_group.read'],
      },
    },
    {
      path: 'layered-keyword-groups',
      name: 'LayeredKeywordGroupManage',
      component: () => import('@/views/admin/project/LayeredKeywordGroupManage.vue'),
      meta: {
        title: '拓词管理',
        icon: 'Collection',
        roles: ['operator', 'delivery_manager', 'manager', 'super_admin'],
        permissions: ['keyword_group.read'],
      },
    },
    {
      path: 'monitoring/platforms',
      name: 'PlatformHealth',
      component: () => import('@/views/admin/monitoring/PlatformHealth.vue'),
      meta: { title: '平台健康', permissions: ['content.read', 'delivery.overview.read', 'user.manage'] },
    },
    {
      path: 'monitoring/question-poll-verification',
      name: 'QuestionPollVerification',
      component: () => import('@/views/admin/monitoring/QuestionPollVerification.vue'),
      meta: { title: '轮询链路验证', hidden: true, permissions: ['dispatch.question_poll.manual'] },
    },
    {
      path: 'reports/:id',
      name: 'ReportPreview',
      component: () => import('@/views/admin/report/ReportPreview.vue'),
      meta: { title: '报表预览', hidden: true, permissions: ['report.review'] },
    },
    {
      path: 'presale/report',
      name: 'PresaleReportList',
      component: () => import('@/views/admin/presale/report/PresaleReportList.vue'),
      meta: {
        title: 'AI可见度诊断报告',
        icon: 'Document',
        permissions: ['presale.report.list'],
      },
    },
    {
      path: 'presale/report/create',
      name: 'PresaleReportCreate',
      component: () => import('@/views/admin/presale/report/PresaleReportCreate.vue'),
      meta: {
        title: '新建报告',
        hidden: true,
        permissions: ['presale.report.create'],
      },
    },
    {
      path: 'presale/report/page03-config',
      name: 'PresalePage03Config',
      component: () => import('@/views/admin/presale/report/PresalePage03Config.vue'),
      meta: {
        title: 'PAGE03 配置',
        hidden: true,
        roles: ['delivery_manager', 'manager', 'super_admin'],
      },
    },
    {
      path: 'presale/report/narrative-config',
      name: 'PresaleNarrativeConfig',
      component: () => import('@/views/admin/presale/report/PresaleNarrativeConfig.vue'),
      meta: {
        title: '诊断文案配置',
        hidden: true,
        roles: ['delivery_manager', 'manager', 'super_admin'],
      },
    },
    {
      path: 'presale/report/benchmark-config',
      name: 'PresaleBenchmarkConfig',
      component: () => import('@/views/admin/presale/report/PresaleBenchmarkConfig.vue'),
      meta: {
        title: '行业基准配置',
        hidden: true,
        roles: ['delivery_manager', 'manager', 'super_admin'],
      },
    },
    {
      path: 'presale/report/:id/progress',
      name: 'PresaleReportProgress',
      component: () => import('@/views/admin/presale/report/PresaleReportProgress.vue'),
      meta: {
        title: '生成进度',
        hidden: true,
        permissions: ['presale.report.view'],
      },
    },
    {
      path: 'presale/report/:id/detail',
      name: 'PresaleReportDetail',
      component: () => import('@/views/admin/presale/report/PresaleReportDetail.vue'),
      meta: {
        title: '报告详情',
        hidden: true,
        permissions: ['presale.report.view'],
      },
    },
    {
      path: 'presale/report/:id/edit',
      name: 'PresaleReportEdit',
      component: () => import('@/views/admin/presale/report/PresaleReportEdit.vue'),
      meta: {
        title: '编辑AI可见度诊断报告',
        hidden: true,
        permissions: ['presale.report.view'],
      },
    },
    {
      path: 'presale/report/:id/versions/:versionNo/prompts',
      name: 'PresaleReportPromptList',
      component: () => import('@/views/admin/presale/report/PresaleReportPromptList.vue'),
      meta: {
        title: 'Prompt 调用记录',
        hidden: true,
        permissions: ['presale.report.view'],
      },
    },
    {
      path: 'presale/report/:id/versions/:versionNo/prompts/:promptResultId',
      name: 'PresaleReportPromptDetail',
      component: () => import('@/views/admin/presale/report/PresaleReportPromptDetail.vue'),
      meta: {
        title: 'Prompt 调用详情',
        hidden: true,
        permissions: ['presale.report.view'],
      },
    },
    {
      path: 'partners',
      name: 'PartnerList',
      component: () => import('@/views/admin/partner/PartnerList.vue'),
      meta: {
        title: '合伙人管理',
        icon: 'Coordinate',
        permissions: ['partner.read'],
      },
    },
    {
      path: 'partners/:id',
      name: 'PartnerDetail',
      component: () => import('@/views/admin/partner/PartnerDetail.vue'),
      meta: { title: '合伙人详情', hidden: true, permissions: ['partner.read'] },
    },
    {
      path: 'alerts',
      name: 'AlertCenter',
      component: () => import('@/views/admin/alert/AlertCenter.vue'),
      meta: { title: '告警中心', icon: 'Bell', permissions: ['content.read', 'content.distribution.retry', 'dispatch.alert.resolve', 'system.alert.resolve'] },
    },
    {
      path: 'activity-logs',
      name: 'ActivityLogs',
      component: () => import('@/views/admin/system/ActivityLogs.vue'),
      meta: { title: '操作日志', icon: 'Document', permissions: ['user.manage'] },
    },
    {
      path: 'model-diagnostics',
      name: 'ModelDiagnosticConsole',
      component: () => import('@/views/admin/system/ModelDiagnosticConsole.vue'),
      meta: { title: '大模型诊断台', icon: 'ChatDotRound', permissions: ['ai.platform.diagnose'] },
    },
    {
      path: 'settings/platforms',
      name: 'PlatformConfig',
      component: () => import('@/views/admin/settings/PlatformConfig.vue'),
      meta: { title: 'AI平台配置', icon: 'Setting', permissions: ['user.manage'] },
    },
    {
      path: 'settings/publish-sites',
      name: 'PublishSiteConfig',
      redirect: '/admin/content/publish-platforms',
      meta: { title: '发布站点配置', hidden: true, permissions: ['user.manage'] },
    },
    {
      path: 'settings/packages',
      name: 'PackageConfig',
      component: () => import('@/views/admin/settings/PackageConfig.vue'),
      meta: { title: '套餐配置', permissions: ['user.manage'] },
    },
    {
      path: 'settings/dicts',
      name: 'DictCenter',
      component: () => import('@/views/admin/settings/DictCenter.vue'),
      meta: { title: '字典中心', permissions: ['user.manage'] },
    },
    {
      path: 'settings/business-calendar',
      name: 'BusinessCalendarManagement',
      component: () => import('@/views/admin/settings/BusinessCalendarManagement.vue'),
      meta: { title: '工作日历', permissions: ['user.manage'] },
    },
    {
      path: 'settings/affix-words',
      name: 'KeywordAffixWordManage',
      component: () => import('@/views/admin/settings/KeywordAffixWordManage.vue'),
      meta: { title: '拓词信息维护', permissions: ['keyword_affix.manage'] },
    },
    {
      path: 'settings/users',
      name: 'UserManage',
      component: () => import('@/views/admin/settings/UserManage.vue'),
      meta: { title: '用户与权限', hidden: true, permissions: ['user.manage'] },
    },
  ],
}

export default adminRoutes
