CREATE TABLE IF NOT EXISTS authority_media_resource (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  resource_type VARCHAR(32) NOT NULL COMMENT 'NEWS_MEDIA/WEMEDIA/VIDEO/OVERSEAS',
  external_resource_id VARCHAR(64) NOT NULL COMMENT '特价网资源 id',
  name VARCHAR(255) NOT NULL COMMENT '媒体/账号/资源名称',
  platform VARCHAR(128) NULL COMMENT '平台，自媒体/短视频资源使用',
  industry VARCHAR(255) NULL COMMENT '行业标签或分类',
  province VARCHAR(255) NULL COMMENT '地区',
  price DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '特价网资源价格',
  status INT NOT NULL DEFAULT 0 COMMENT '远端状态，1 通常表示上架',
  pc_weight INT NULL COMMENT '电脑权重',
  m_weight INT NULL COMMENT '移动权重',
  news_resource INT NULL COMMENT '新闻源枚举',
  entrance_level INT NULL COMMENT '入口级别',
  include_condition INT NULL COMMENT '收录情况',
  publication_time INT NULL COMMENT '发稿速度',
  weekend_publish INT NULL COMMENT '周末可发',
  publish_rate VARCHAR(64) NULL COMMENT '出稿率',
  inclusion_rate INT NULL COMMENT '收录率 0-100',
  remark TEXT NULL COMMENT '远端备注',
  uptime BIGINT NULL COMMENT '远端变动时间戳',
  raw_payload JSON NULL COMMENT '远端原始资源数据',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL COMMENT '本地软下架/远端对账下架时间',
  UNIQUE KEY uk_authority_media_resource_external (resource_type, external_resource_id),
  KEY idx_authority_media_resource_type_status (resource_type, status, deleted_at),
  KEY idx_authority_media_resource_uptime (resource_type, uptime),
  KEY idx_authority_media_resource_price (resource_type, price)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='特价网资源缓存，一期仅开放 NEWS_MEDIA';

CREATE TABLE IF NOT EXISTS authority_media_order (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  distribution_task_id BIGINT UNSIGNED NULL,
  article_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT NOT NULL,
  resource_id BIGINT NOT NULL,
  resource_type VARCHAR(32) NOT NULL COMMENT 'NEWS_MEDIA/WEMEDIA/VIDEO/OVERSEAS',
  external_no VARCHAR(64) NULL COMMENT '传给特价网的稳定订单号，如 AM-{id}',
  submit_status VARCHAR(32) NOT NULL DEFAULT 'created' COMMENT 'created/submitting/submitted/submit_failed',
  remote_status INT NULL COMMENT '特价网原始订单状态 -2/-1/0/1/2',
  remote_status_text VARCHAR(64) NULL,
  published_url VARCHAR(1024) NULL,
  reject_reason VARCHAR(1000) NULL,
  remote_published_at DATETIME NULL,
  submitted_at DATETIME NULL,
  last_checked_at DATETIME NULL,
  next_check_at DATETIME NULL,
  request_payload TEXT NULL,
  response_payload TEXT NULL,
  extra_payload JSON NULL COMMENT '海外媒体 present_url/others 等类型特定字段',
  lock_version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_authority_media_order_external_no (external_no),
  UNIQUE KEY uk_authority_media_order_task (distribution_task_id),
  KEY idx_authority_media_order_article (article_id, created_at),
  KEY idx_authority_media_order_project (project_id, created_at),
  KEY idx_authority_media_order_resource (resource_id, created_at),
  KEY idx_authority_media_order_check (submit_status, remote_status, next_check_at),
  CONSTRAINT fk_authority_media_order_task FOREIGN KEY (distribution_task_id) REFERENCES distribution_tasks(id),
  CONSTRAINT fk_authority_media_order_article FOREIGN KEY (article_id) REFERENCES article_draft(id),
  CONSTRAINT fk_authority_media_order_project FOREIGN KEY (project_id) REFERENCES project(id),
  CONSTRAINT fk_authority_media_order_resource FOREIGN KEY (resource_id) REFERENCES authority_media_resource(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='特价网资源采购订单；同一 distribution_task 仅对应一条 order 记录；远端拒稿/删除后由用户改稿重发的场景需新建 distribution_task，order 不复用';

CREATE TABLE IF NOT EXISTS meititejia_enum (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  enum_type VARCHAR(64) NOT NULL,
  enum_key VARCHAR(64) NOT NULL,
  enum_value VARCHAR(255) NOT NULL,
  raw_payload JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_meititejia_enum_type_key (enum_type, enum_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='特价网 get_enum 字典缓存';
