CREATE TABLE IF NOT EXISTS baseline_report_poll_batch (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    project_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL COMMENT 'running|completed|failed',
    selected_platform_codes JSON NOT NULL,
    selected_question_tiers JSON NOT NULL,
    platform_count INT NOT NULL DEFAULT 0,
    question_count INT NOT NULL DEFAULT 0,
    total_count INT NOT NULL DEFAULT 0,
    completed_count INT NOT NULL DEFAULT 0,
    failed_count INT NOT NULL DEFAULT 0,
    error_message TEXT NULL,
    created_by BIGINT NULL,
    started_at DATETIME NOT NULL,
    finished_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_baseline_batch_project_created (project_id, created_at),
    CONSTRAINT fk_baseline_batch_project FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='baseline report manual poll batches';

CREATE TABLE IF NOT EXISTS baseline_report_poll_result (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    batch_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    keyword_result_id BIGINT NOT NULL,
    question_tier VARCHAR(4) NOT NULL,
    question_text TEXT NOT NULL,
    platform_id BIGINT NOT NULL,
    platform_code VARCHAR(64) NOT NULL,
    platform_name VARCHAR(128) NULL,
    status VARCHAR(32) NOT NULL COMMENT 'completed|failed',
    request_count INT NOT NULL DEFAULT 0,
    response_time_ms BIGINT NULL,
    response_text MEDIUMTEXT NULL,
    error_message TEXT NULL,
    detail_json JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_baseline_result_unique (batch_id, keyword_result_id, platform_id),
    KEY idx_baseline_result_project_batch (project_id, batch_id),
    KEY idx_baseline_result_platform (platform_id),
    CONSTRAINT fk_baseline_result_batch FOREIGN KEY (batch_id) REFERENCES baseline_report_poll_batch(id) ON DELETE CASCADE,
    CONSTRAINT fk_baseline_result_project FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE,
    CONSTRAINT fk_baseline_result_keyword FOREIGN KEY (keyword_result_id) REFERENCES keyword_group_result(id) ON DELETE CASCADE,
    CONSTRAINT fk_baseline_result_platform FOREIGN KEY (platform_id) REFERENCES ai_platform_config(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='baseline report question x platform poll results';
