CREATE TABLE IF NOT EXISTS batch_article_generation_batch (
  id                  BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  project_id          BIGINT          NOT NULL,
  company_id          BIGINT          NULL,
  brand_id            BIGINT UNSIGNED NULL,
  topic_source        VARCHAR(32)     NOT NULL DEFAULT 'manual',
  topic               VARCHAR(1000)   NOT NULL,
  topic_as_question   VARCHAR(1000)   NULL,
  keyword_group_id    BIGINT UNSIGNED NULL,
  keyword_group_name  VARCHAR(255)    NULL,
  total_count         INT             NOT NULL DEFAULT 0,
  success_count       INT             NOT NULL DEFAULT 0,
  failed_count        INT             NOT NULL DEFAULT 0,
  warning_count       INT             NOT NULL DEFAULT 0,
  status              VARCHAR(32)     NOT NULL DEFAULT 'pending',
  created_by          BIGINT          NULL,
  created_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  started_at          DATETIME        NULL,
  finished_at         DATETIME        NULL,
  error_message       VARCHAR(1000)   NULL,
  KEY idx_batch_article_project_created (project_id, created_at),
  KEY idx_batch_article_status (status, created_at),
  CONSTRAINT fk_batch_article_project FOREIGN KEY (project_id) REFERENCES project(id),
  CONSTRAINT fk_batch_article_user FOREIGN KEY (created_by) REFERENCES sys_user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='manual batch article generation batch';

CREATE TABLE IF NOT EXISTS batch_article_generation_task (
  id                       BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  batch_id                 BIGINT UNSIGNED NOT NULL,
  project_id               BIGINT          NOT NULL,
  article_id               BIGINT UNSIGNED NULL,
  row_no                   INT             NOT NULL,
  article_index_in_row     INT             NOT NULL,
  article_index_in_batch   INT             NOT NULL,
  article_type             VARCHAR(32)     NOT NULL,
  tone                     VARCHAR(32)     NOT NULL,
  content_style            VARCHAR(32)     NOT NULL,
  length                   VARCHAR(32)     NOT NULL DEFAULT 'medium',
  topic                    VARCHAR(1000)   NOT NULL,
  topic_as_question        VARCHAR(1000)   NULL,
  content_angle            VARCHAR(64)     NULL,
  audience_perspective     VARCHAR(255)    NULL,
  extra_prompt             VARCHAR(3000)   NULL,
  status                   VARCHAR(32)     NOT NULL DEFAULT 'pending',
  quality_status           VARCHAR(32)     NULL,
  quality_issues_json      JSON            NULL,
  prompt_snapshot          JSON            NULL,
  input_snapshot           JSON            NULL,
  response_snapshot        JSON            NULL,
  model_platform_code      VARCHAR(64)     NULL,
  model_id                 VARCHAR(128)    NULL,
  error_message            VARCHAR(1000)   NULL,
  retry_count              INT             NOT NULL DEFAULT 0,
  created_at               DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at               DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  started_at               DATETIME        NULL,
  finished_at              DATETIME        NULL,
  UNIQUE KEY uk_batch_article_task_index (batch_id, article_index_in_batch),
  KEY idx_batch_article_task_batch_status (batch_id, status),
  KEY idx_batch_article_task_article (article_id),
  CONSTRAINT fk_batch_article_task_batch FOREIGN KEY (batch_id) REFERENCES batch_article_generation_batch(id),
  CONSTRAINT fk_batch_article_task_project FOREIGN KEY (project_id) REFERENCES project(id),
  CONSTRAINT fk_batch_article_task_article FOREIGN KEY (article_id) REFERENCES article_draft(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='manual batch article generation task';
