-- ============================================================
-- V189: content auto distribution plans
-- ============================================================

CREATE TABLE IF NOT EXISTS content_auto_distribution_batch (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  project_id BIGINT NOT NULL,
  company_id BIGINT NULL,
  brand_id BIGINT UNSIGNED NULL,
  plan_date DATE NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'created' COMMENT 'created/generating/publish_scheduled/completed/partial_failed/failed/skipped',
  total_count INT NOT NULL DEFAULT 0,
  generated_count INT NOT NULL DEFAULT 0,
  scheduled_count INT NOT NULL DEFAULT 0,
  failed_count INT NOT NULL DEFAULT 0,
  error_message VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_auto_distribution_project_date (project_id, plan_date),
  KEY idx_auto_distribution_batch_status (status, plan_date),
  CONSTRAINT fk_auto_distribution_batch_project FOREIGN KEY (project_id) REFERENCES project(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='content auto distribution batch';

CREATE TABLE IF NOT EXISTS content_auto_distribution_item (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT NOT NULL,
  company_id BIGINT NULL,
  brand_id BIGINT UNSIGNED NULL,
  plan_date DATE NOT NULL,
  channel_code VARCHAR(32) NOT NULL COMMENT 'official_site/industry_site/forum',
  channel_group_code VARCHAR(32) NOT NULL COMMENT 'agent_site/industry_site/forum',
  content_style VARCHAR(64) NOT NULL,
  target_kind VARCHAR(32) NOT NULL COMMENT 'brand_geo_site/industry_site/forum_site',
  target_id BIGINT UNSIGNED NULL,
  target_name VARCHAR(160) NULL,
  target_brand_id BIGINT NULL,
  target_forum_fid INT NULL,
  sequence_no INT NOT NULL,
  question_id BIGINT UNSIGNED NULL,
  question_text VARCHAR(1000) NOT NULL,
  generation_batch_id BIGINT UNSIGNED NULL,
  generation_task_id BIGINT UNSIGNED NULL,
  article_id BIGINT UNSIGNED NULL,
  publish_job_id BIGINT NULL,
  publish_item_id BIGINT NULL,
  planned_publish_at DATETIME NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending_generation',
  failure_reason VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_auto_distribution_target_seq (project_id, plan_date, channel_code, target_kind, target_id, sequence_no),
  KEY idx_auto_distribution_item_batch_status (batch_id, status),
  KEY idx_auto_distribution_item_generation_task (generation_task_id),
  KEY idx_auto_distribution_item_publish_item (publish_item_id),
  CONSTRAINT fk_auto_distribution_item_batch FOREIGN KEY (batch_id) REFERENCES content_auto_distribution_batch(id),
  CONSTRAINT fk_auto_distribution_item_project FOREIGN KEY (project_id) REFERENCES project(id),
  CONSTRAINT fk_auto_distribution_item_generation_batch FOREIGN KEY (generation_batch_id) REFERENCES batch_article_generation_batch(id),
  CONSTRAINT fk_auto_distribution_item_generation_task FOREIGN KEY (generation_task_id) REFERENCES batch_article_generation_task(id),
  CONSTRAINT fk_auto_distribution_item_article FOREIGN KEY (article_id) REFERENCES article_draft(id),
  CONSTRAINT fk_auto_distribution_item_publish_job FOREIGN KEY (publish_job_id) REFERENCES content_batch_publish_job(id),
  CONSTRAINT fk_auto_distribution_item_publish_item FOREIGN KEY (publish_item_id) REFERENCES content_batch_publish_item(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='content auto distribution item';
