CREATE TABLE IF NOT EXISTS local_agent_session (
  id BIGINT NOT NULL AUTO_INCREMENT,
  brand_id BIGINT NOT NULL,
  operator_id BIGINT NOT NULL,
  access_token_lookup_hash VARCHAR(64) NOT NULL,
  access_token_hash VARCHAR(64) NOT NULL,
  access_token_hash_alg VARCHAR(16) NOT NULL DEFAULT 'SHA-256',
  access_token_salt VARCHAR(64) NOT NULL,
  hmac_secret VARCHAR(128) NOT NULL,
  device_secret_hash VARCHAR(64) NULL,
  helper_name VARCHAR(128) NULL,
  user_agent VARCHAR(512) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  bound_at DATETIME NOT NULL,
  last_seen_at DATETIME NULL,
  expires_at DATETIME NOT NULL,
  revoked_at DATETIME NULL,
  revoked_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_local_agent_session_lookup_hash (access_token_lookup_hash),
  KEY idx_local_agent_brand_status (brand_id, status),
  KEY idx_local_agent_operator_status (operator_id, status),
  CONSTRAINT fk_local_agent_session_brand FOREIGN KEY (brand_id) REFERENCES brand(id),
  CONSTRAINT fk_local_agent_session_operator FOREIGN KEY (operator_id) REFERENCES sys_user(id),
  CONSTRAINT fk_local_agent_session_revoked_by FOREIGN KEY (revoked_by) REFERENCES sys_user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='local helper C2 sessions';
