-- Enable Xiaohongshu manual/automatic schedule creation after AdsPower automation validation.

INSERT INTO self_media_schedule_capability (
  platform,
  verification_status,
  supports_schedule,
  min_delay_minutes,
  max_delay_minutes,
  save_creates_schedule,
  supports_cancel,
  supports_modify,
  supports_publish_check,
  v1_strategy,
  selector_status,
  evidence_json,
  notes,
  verified_at,
  verified_by,
  created_at,
  updated_at
) VALUES (
  'xiaohongshu',
  'verified',
  1,
  60,
  20160,
  1,
  0,
  0,
  1,
  'platform_schedule',
  'needs_runtime_verification',
  JSON_OBJECT(
    'source', 'ads_power_automation',
    'flow', JSON_ARRAY('one_click_format', 'next_step', 'schedule_publish', 'publish_success'),
    'minDelayMinutes', 60,
    'maxDelayMinutes', 20160,
    'locationRequired', false,
    'coverRequired', false
  ),
  '小红书 AdsPower 自动化已接入，支持一键排版后设置平台原生定时发布；地点与封面不作为必填项。',
  CURRENT_TIMESTAMP,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
) ON DUPLICATE KEY UPDATE
  verification_status = VALUES(verification_status),
  supports_schedule = VALUES(supports_schedule),
  min_delay_minutes = VALUES(min_delay_minutes),
  max_delay_minutes = VALUES(max_delay_minutes),
  save_creates_schedule = VALUES(save_creates_schedule),
  supports_cancel = VALUES(supports_cancel),
  supports_modify = VALUES(supports_modify),
  supports_publish_check = VALUES(supports_publish_check),
  v1_strategy = VALUES(v1_strategy),
  selector_status = VALUES(selector_status),
  evidence_json = VALUES(evidence_json),
  notes = VALUES(notes),
  verified_at = COALESCE(verified_at, VALUES(verified_at)),
  updated_at = CURRENT_TIMESTAMP;
