-- Enable Baijiahao platform-native schedule creation after AdsPower automation wiring.

INSERT INTO self_media_schedule_capability (
  platform,
  verification_status,
  supports_schedule,
  min_delay_minutes,
  max_delay_minutes,
  save_creates_schedule,
  supports_cancel,
  supports_modify,
  supports_publish_check,
  v1_strategy,
  selector_status,
  evidence_json,
  notes,
  verified_at,
  verified_by,
  created_at,
  updated_at
) VALUES (
  'baijiahao',
  'verified',
  1,
  60,
  10080,
  1,
  0,
  0,
  1,
  'platform_schedule',
  'needs_runtime_verification',
  JSON_OBJECT(
    'source', 'ads_power_automation',
    'flow', JSON_ARRAY('fill_title_content', 'upload_single_cover', 'schedule_publish'),
    'publishUrl', 'https://baijiahao.baidu.com/builder/rc/edit?type=news&is_from_cms=1',
    'minDelayMinutes', 60,
    'maxDelayMinutes', 10080,
    'locationRequired', false,
    'coverRequired', true
  ),
  '百家号 AdsPower 自动化已接入基础链路：标题正文填充、单图封面上传、平台原生定时发布；作品列表回查需结合真实任务继续校准。',
  CURRENT_TIMESTAMP,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
) ON DUPLICATE KEY UPDATE
  verification_status = VALUES(verification_status),
  supports_schedule = VALUES(supports_schedule),
  min_delay_minutes = VALUES(min_delay_minutes),
  max_delay_minutes = VALUES(max_delay_minutes),
  save_creates_schedule = VALUES(save_creates_schedule),
  supports_cancel = VALUES(supports_cancel),
  supports_modify = VALUES(supports_modify),
  supports_publish_check = VALUES(supports_publish_check),
  v1_strategy = VALUES(v1_strategy),
  selector_status = VALUES(selector_status),
  evidence_json = VALUES(evidence_json),
  notes = VALUES(notes),
  verified_at = COALESCE(verified_at, VALUES(verified_at)),
  updated_at = CURRENT_TIMESTAMP;
