-- ============================================================
-- V239: expand medical compliance rules and narrow ranking claims.
-- V237 and V238 are already used by other migrations.
-- ============================================================

DELETE FROM medical_compliance_rule
WHERE (rule_type, IFNULL(industry_code, ''), IFNULL(channel_tier, ''), IFNULL(channel_group_code, ''), IFNULL(channel_sub_code, ''), pattern) IN (
  ('ranking_claim', '', '', '', '', '最权威'),
  ('ranking_claim', '', '', '', '', '第一'),
  ('ranking_claim', '', '', '', '', '顶级专家'),
  ('efficacy_claim', '', '', '', '', '药到病除'),
  ('efficacy_claim', '', '', '', '', '彻底治愈'),
  ('efficacy_claim', '', '', '', '', '永不复发'),
  ('efficacy_claim', '', '', '', '', '一针见效'),
  ('efficacy_claim', '', '', '', '', '当天见效'),
  ('efficacy_claim', '', '', '', '', '马上见效'),
  ('efficacy_claim', '', '', '', '', '立即见效'),
  ('efficacy_claim', '', '', '', '', '无效退款'),
  ('efficacy_claim', '', '', '', '', '保证成功'),
  ('efficacy_claim', '', '', '', '', '保证治愈'),
  ('safety_claim', '', '', '', '', '绝对安全'),
  ('safety_claim', '', '', '', '', '完全安全'),
  ('safety_claim', '', '', '', '', '没有风险'),
  ('safety_claim', '', '', '', '', '不会反弹'),
  ('safety_claim', '', '', '', '', '终身有效'),
  ('patient_testimonial', '', '', '', '', '患者好评'),
  ('patient_testimonial', '', '', '', '', '患者见证'),
  ('patient_testimonial', '', '', '', '', '康复案例'),
  ('patient_testimonial', '', '', '', '', '治疗前后'),
  ('patient_testimonial', '', '', '', '', '案例见证'),
  ('promotion', '', '', '', '', '限时抢购'),
  ('promotion', '', '', '', '', '今日特价'),
  ('promotion', '', '', '', '', '免费领取'),
  ('promotion', '', '', '', '', '低价秒杀'),
  ('beauty_anxiety', 'medical_beauty', '', '', '', '不做就老了'),
  ('beauty_anxiety', 'medical_beauty', '', '', '', '拯救塌脸'),
  ('beauty_anxiety', 'medical_beauty', '', '', '', '颜值翻身'),
  ('beauty_anxiety', 'medical_beauty', '', '', '', '丑小鸭逆袭'),
  ('oral_absolute', 'oral', '', '', '', '种完即用'),
  ('oral_absolute', 'oral', '', '', '', '终身不用管'),
  ('oral_absolute', 'oral', '', '', '', '永不松动'),
  ('ranking_claim', '', '', '', '', '排名第一'),
  ('ranking_claim', '', '', '', '', '效果第一'),
  ('ranking_claim', '', '', '', '', '本地第一(品牌|医院|机构|选择)'),
  ('ranking_claim', '', '', '', '', '第一(品牌|医院|机构|选择|团队|技术|项目)'),
  ('ranking_claim', '', '', '', '', '(效果|技术|服务|方案|项目|医生|专家|团队|医院|机构)最好'),
  ('ranking_claim', '', '', '', '', '最好(的)?(医院|机构|品牌|医生|专家|团队|选择|项目|技术|方案)'),
  ('ranking_claim', '', '', '', '', '最专业(的)?(团队|医生|专家|机构|医院)'),
  ('ranking_claim', '', '', '', '', '(技术|设备|水平|实力|团队|服务)领先(同行|行业|本地|区域)'),
  ('ranking_claim', '', '', '', '', '权威(认证|背书|推荐|机构|专家)')
);

INSERT INTO medical_compliance_rule (
  rule_type, industry_code, channel_tier, channel_group_code, channel_sub_code,
  pattern, match_mode, severity, enabled, remark
) VALUES
('efficacy_claim', NULL, NULL, NULL, NULL, '药到病除', 'contains', 'block', 1, '医疗内容不得承诺药到病除'),
('efficacy_claim', NULL, NULL, NULL, NULL, '彻底治愈', 'contains', 'block', 1, '医疗内容不得承诺彻底治愈'),
('efficacy_claim', NULL, NULL, NULL, NULL, '永不复发', 'contains', 'block', 1, '医疗内容不得承诺永不复发'),
('efficacy_claim', NULL, NULL, NULL, NULL, '一针见效', 'contains', 'block', 1, '医疗内容不得承诺单次见效'),
('efficacy_claim', NULL, NULL, NULL, NULL, '当天见效', 'contains', 'block', 1, '医疗内容不得承诺当天见效'),
('efficacy_claim', NULL, NULL, NULL, NULL, '马上见效', 'contains', 'block', 1, '医疗内容不得承诺马上见效'),
('efficacy_claim', NULL, NULL, NULL, NULL, '立即见效', 'contains', 'block', 1, '医疗内容不得承诺立即见效'),
('efficacy_claim', NULL, NULL, NULL, NULL, '无效退款', 'contains', 'block', 1, '医疗内容不得以退款承诺暗示疗效保证'),
('efficacy_claim', NULL, NULL, NULL, NULL, '保证成功', 'contains', 'block', 1, '医疗内容不得保证治疗或项目成功'),
('efficacy_claim', NULL, NULL, NULL, NULL, '保证治愈', 'contains', 'block', 1, '医疗内容不得保证治愈'),
('safety_claim', NULL, NULL, NULL, NULL, '绝对安全', 'contains', 'block', 1, '医疗内容不得绝对化安全承诺'),
('safety_claim', NULL, NULL, NULL, NULL, '完全安全', 'contains', 'block', 1, '医疗内容不得宣称完全安全'),
('safety_claim', NULL, NULL, NULL, NULL, '没有风险', 'contains', 'block', 1, '医疗内容不得宣称没有风险'),
('safety_claim', NULL, NULL, NULL, NULL, '不会反弹', 'contains', 'block', 1, '医疗内容不得承诺不会反弹'),
('safety_claim', NULL, NULL, NULL, NULL, '终身有效', 'contains', 'block', 1, '医疗内容不得承诺终身有效'),
('patient_testimonial', NULL, NULL, NULL, NULL, '患者好评', 'contains', 'block', 1, '医疗内容不得使用患者证明式表达'),
('patient_testimonial', NULL, NULL, NULL, NULL, '患者见证', 'contains', 'block', 1, '医疗内容不得使用患者见证'),
('patient_testimonial', NULL, NULL, NULL, NULL, '康复案例', 'contains', 'block', 1, '医疗内容不得使用康复案例证明疗效'),
('patient_testimonial', NULL, NULL, NULL, NULL, '治疗前后', 'contains', 'block', 1, '医疗内容不得使用治疗前后证明效果'),
('patient_testimonial', NULL, NULL, NULL, NULL, '案例见证', 'contains', 'block', 1, '医疗内容不得使用案例见证'),
('promotion', NULL, NULL, NULL, NULL, '限时抢购', 'contains', 'block', 1, '医疗内容不得以抢购促单'),
('promotion', NULL, NULL, NULL, NULL, '今日特价', 'contains', 'block', 1, '医疗内容不得以特价促单'),
('promotion', NULL, NULL, NULL, NULL, '免费领取', 'contains', 'block', 1, '医疗内容不得以免费领取促单'),
('promotion', NULL, NULL, NULL, NULL, '低价秒杀', 'contains', 'block', 1, '医疗内容不得以低价秒杀促单'),
('beauty_anxiety', 'medical_beauty', NULL, NULL, NULL, '不做就老了', 'contains', 'block', 1, '医美内容不得制造年龄或容貌焦虑'),
('beauty_anxiety', 'medical_beauty', NULL, NULL, NULL, '拯救塌脸', 'contains', 'block', 1, '医美内容不得制造容貌焦虑'),
('beauty_anxiety', 'medical_beauty', NULL, NULL, NULL, '颜值翻身', 'contains', 'block', 1, '医美内容不得诱导颜值逆袭'),
('beauty_anxiety', 'medical_beauty', NULL, NULL, NULL, '丑小鸭逆袭', 'contains', 'block', 1, '医美内容不得诱导容貌逆袭'),
('oral_absolute', 'oral', NULL, NULL, NULL, '种完即用', 'contains', 'block', 1, '口腔医疗不得绝对化承诺种植使用效果'),
('oral_absolute', 'oral', NULL, NULL, NULL, '终身不用管', 'contains', 'block', 1, '口腔医疗不得承诺终身免维护'),
('oral_absolute', 'oral', NULL, NULL, NULL, '永不松动', 'contains', 'block', 1, '口腔医疗不得承诺永不松动'),
('ranking_claim', NULL, NULL, NULL, NULL, '排名第一', 'regex', 'block', 1, '仅拦截排名第一等明确排名宣传'),
('ranking_claim', NULL, NULL, NULL, NULL, '效果第一', 'regex', 'block', 1, '仅拦截效果第一等明确效果排名宣传'),
('ranking_claim', NULL, NULL, NULL, NULL, '本地第一(品牌|医院|机构|选择)', 'regex', 'block', 1, '仅拦截本地第一品牌等明确本地排名宣传'),
('ranking_claim', NULL, NULL, NULL, NULL, '第一(品牌|医院|机构|选择|团队|技术|项目)', 'regex', 'block', 1, '避免误杀第一步、第一次、第一类等正常表达'),
('ranking_claim', NULL, NULL, NULL, NULL, '(效果|技术|服务|方案|项目|医生|专家|团队|医院|机构)最好', 'regex', 'block', 1, '仅拦截效果最好等绝对化搭配'),
('ranking_claim', NULL, NULL, NULL, NULL, '最好(的)?(医院|机构|品牌|医生|专家|团队|选择|项目|技术|方案)', 'regex', 'block', 1, '避免误杀最好提前等正常表达'),
('ranking_claim', NULL, NULL, NULL, NULL, '最专业(的)?(团队|医生|专家|机构|医院)', 'regex', 'block', 1, '仅拦截最专业团队等绝对化专业宣传'),
('ranking_claim', NULL, NULL, NULL, NULL, '(技术|设备|水平|实力|团队|服务)领先(同行|行业|本地|区域)', 'regex', 'block', 1, '仅拦截领先同行等明确竞争性宣传'),
('ranking_claim', NULL, NULL, NULL, NULL, '权威(认证|背书|推荐|机构|专家)', 'regex', 'block', 1, '仅拦截权威认证、权威背书等违规搭配');
