-- Switch Douyin article publishing from Open Platform API scheduling to AdsPower browser automation.

INSERT INTO self_media_schedule_capability (
  platform,
  verification_status,
  supports_schedule,
  min_delay_minutes,
  max_delay_minutes,
  save_creates_schedule,
  supports_cancel,
  supports_modify,
  supports_publish_check,
  v1_strategy,
  selector_status,
  evidence_json,
  notes,
  verified_at,
  verified_by,
  created_at,
  updated_at
) VALUES (
  'douyin',
  'verified',
  1,
  120,
  20160,
  1,
  0,
  0,
  1,
  'platform_schedule',
  'needs_runtime_verification',
  JSON_OBJECT(
    'source', 'ads_power_automation',
    'flow', JSON_ARRAY('open_article_tab', 'fill_title_content', 'upload_head_image', 'upload_cover', 'schedule_publish', 'refresh_manage_page_check'),
    'publishUrl', 'https://creator.douyin.com/creator-micro/content/upload',
    'manageUrl', 'https://creator.douyin.com/creator-micro/content/manage',
    'minDelayMinutes', 120,
    'maxDelayMinutes', 20160,
    'coverRequired', true,
    'headImageOptionalWhenNoDifferentCoverMaterial', true
  ),
  '抖音文章切换为 AdsPower 指纹浏览器自动化：标题自动截断 30 字，摘要/话题/配乐暂跳过，头图优先取不同于封面的图库图片，平台定时支持 2 小时后至 14 天内。',
  CURRENT_TIMESTAMP,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
) ON DUPLICATE KEY UPDATE
  verification_status = VALUES(verification_status),
  supports_schedule = VALUES(supports_schedule),
  min_delay_minutes = VALUES(min_delay_minutes),
  max_delay_minutes = VALUES(max_delay_minutes),
  save_creates_schedule = VALUES(save_creates_schedule),
  supports_cancel = VALUES(supports_cancel),
  supports_modify = VALUES(supports_modify),
  supports_publish_check = VALUES(supports_publish_check),
  v1_strategy = VALUES(v1_strategy),
  selector_status = VALUES(selector_status),
  evidence_json = VALUES(evidence_json),
  notes = VALUES(notes),
  verified_at = COALESCE(verified_at, VALUES(verified_at)),
  updated_at = CURRENT_TIMESTAMP;
