CREATE TABLE IF NOT EXISTS llm_call_observation (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    run_id VARCHAR(96) NULL COMMENT 'batch/run identifier',
    customer_id BIGINT NULL COMMENT 'customer id',
    project_id BIGINT NULL COMMENT 'project id',
    scope VARCHAR(32) NULL COMMENT 'GLOBAL/INDUSTRY/CUSTOMER/PROJECT/BASELINE_RUN',
    normalized_prompt_hash VARCHAR(128) NULL COMMENT 'normalized prompt hash, no raw prompt',
    feature VARCHAR(64) NULL COMMENT 'LLM feature',
    platform_code VARCHAR(64) NULL COMMENT 'AI platform code',
    platform_name VARCHAR(128) NULL COMMENT 'AI platform name',
    model_id VARCHAR(128) NULL COMMENT 'model id',
    model_name VARCHAR(128) NULL COMMENT 'model name',
    governance_stack VARCHAR(32) NULL COMMENT 'GATEWAY/LEGACY_LIMITER/NO_PERMIT_LEGACY',
    routing_strategy VARCHAR(64) NULL COMMENT 'routing strategy',
    wait_semantics VARCHAR(32) NULL COMMENT 'wait semantics',
    status VARCHAR(32) NOT NULL COMMENT 'success/failure',
    error_category VARCHAR(64) NULL COMMENT 'structured error category',
    http_status_code INT NULL COMMENT 'HTTP status code when available',
    provider_error_code VARCHAR(128) NULL COMMENT 'provider error code when available',
    retry_after_ms BIGINT NULL COMMENT 'Retry-After parsed as milliseconds',
    failure_kind VARCHAR(64) NULL COMMENT 'route failure kind when available',
    request_count INT NULL COMMENT 'attempted request count',
    wait_ms BIGINT NULL COMMENT 'capacity wait/throttle duration',
    http_ms BIGINT NULL COMMENT 'HTTP transport duration',
    total_ms BIGINT NULL COMMENT 'facade total duration',
    prompt_tokens INT NULL COMMENT 'prompt tokens',
    completion_tokens INT NULL COMMENT 'completion tokens',
    total_tokens INT NULL COMMENT 'total tokens',
    estimated_cost DECIMAL(18,6) NULL COMMENT 'estimated cost',
    currency VARCHAR(16) NULL COMMENT 'cost currency',
    occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'event occurrence time',
    KEY idx_llm_call_obs_run_time (run_id, occurred_at),
    KEY idx_llm_call_obs_platform_time (platform_code, occurred_at),
    KEY idx_llm_call_obs_feature_time (feature, occurred_at),
    KEY idx_llm_call_obs_hash_scope (normalized_prompt_hash, scope)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='LLM call measurement observations';

CREATE TABLE IF NOT EXISTS llm_capacity_minute_metric (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    run_id VARCHAR(96) NOT NULL DEFAULT 'ad_hoc' COMMENT 'batch/run identifier',
    bucket_minute DATETIME NOT NULL COMMENT 'minute bucket',
    platform_code VARCHAR(64) NOT NULL DEFAULT 'unknown' COMMENT 'AI platform code',
    feature VARCHAR(64) NOT NULL DEFAULT 'generic' COMMENT 'LLM feature',
    governance_stack VARCHAR(32) NOT NULL DEFAULT 'GATEWAY' COMMENT 'governance stack',
    global_active_peak BIGINT NOT NULL DEFAULT 0 COMMENT 'global permit active peak',
    feature_active_peak BIGINT NOT NULL DEFAULT 0 COMMENT 'feature permit active peak',
    platform_active_peak BIGINT NOT NULL DEFAULT 0 COMMENT 'platform permit active peak',
    permit_busy_count BIGINT NOT NULL DEFAULT 0 COMMENT 'permit busy count',
    permit_waiter_peak BIGINT NOT NULL DEFAULT 0 COMMENT 'permit waiter peak',
    internal_rate_limited_count BIGINT NOT NULL DEFAULT 0 COMMENT 'internal rate limited count',
    platform429_count BIGINT NOT NULL DEFAULT 0 COMMENT 'platform 429 count',
    http5xx_count BIGINT NOT NULL DEFAULT 0 COMMENT 'HTTP 5xx count',
    timeout_count BIGINT NOT NULL DEFAULT 0 COMMENT 'timeout count',
    legacy_rate_limited_count BIGINT NOT NULL DEFAULT 0 COMMENT 'legacy rate limited count',
    legacy_concurrency_waiter_peak BIGINT NOT NULL DEFAULT 0 COMMENT 'legacy concurrency waiter peak',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated time',
    UNIQUE KEY uk_llm_capacity_minute (run_id, bucket_minute, platform_code, feature, governance_stack),
    KEY idx_llm_capacity_minute_time (bucket_minute),
    KEY idx_llm_capacity_minute_run (run_id, bucket_minute)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='LLM capacity minute metrics';
