-- Raw V2 browser observation samples are appended once per environment observation.
-- Raw samples are retained for 14 days by BrowserMetricSampleRetentionJob.

CREATE TABLE local_agent_browser_metric_sample (
  id                              BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  local_agent_session_id          BIGINT       NULL,
  machine_id                      VARCHAR(128) NOT NULL,
  active_profile                  VARCHAR(32)  NOT NULL,
  helper_boot_id                  VARCHAR(64)  NOT NULL,
  browser_environment_id          BIGINT       NULL,
  environment_key                 VARCHAR(128) NULL,
  provider_profile_id             VARCHAR(128) NOT NULL,
  browser_session_epoch           VARCHAR(64)  NULL,
  observed_at                     DATETIME(3)  NOT NULL,
  observed_at_epoch_ms            BIGINT       NOT NULL,
  observation_status              VARCHAR(16)  NOT NULL,
  last_successful_observed_at      DATETIME(3)  NULL,
  failed_probe_duration_ms        INT          NULL,
  helper_uptime_seconds           BIGINT       NULL,
  retained_task_count             INT          NULL,
  active_task_count               INT          NULL,
  claimed_total                   BIGINT       NOT NULL DEFAULT 0,
  execution_claimed_total         BIGINT       NOT NULL DEFAULT 0,
  execution_started_total         BIGINT       NOT NULL DEFAULT 0,
  publish_check_claimed_total     BIGINT       NOT NULL DEFAULT 0,
  publish_check_started_total     BIGINT       NOT NULL DEFAULT 0,
  completed_total                 BIGINT       NOT NULL DEFAULT 0,
  failed_total                    BIGINT       NOT NULL DEFAULT 0,
  total_target_count              INT          NULL,
  managed_target_count            INT          NULL,
  operator_target_count           INT          NULL,
  unknown_target_count            INT          NULL,
  process_rss_bytes               BIGINT       NULL,
  process_cpu_percent             DOUBLE       NULL,
  process_handle_count            INT          NULL,
  cdp_connect_ms                  INT          NULL,
  cdp_browser_get_version_ms      INT          NULL,
  cdp_browser_pages_ms            INT          NULL,
  network_enable_timeout_count    INT          NOT NULL DEFAULT 0,
  cdp_disconnect_count            INT          NOT NULL DEFAULT 0,
  extension_injection_error_count INT          NOT NULL DEFAULT 0,
  page_timeout_count              INT          NOT NULL DEFAULT 0,
  cdp_protocol_timeout_count      INT          NOT NULL DEFAULT 0,
  metrics_json                    JSON         NOT NULL,
  created_at                      DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_browser_metric_observation (
    machine_id,
    active_profile,
    helper_boot_id,
    provider_profile_id,
    observed_at_epoch_ms
  ),
  KEY idx_browser_metric_environment_time (browser_environment_id, observed_at),
  KEY idx_browser_metric_profile_time (provider_profile_id, observed_at),
  KEY idx_browser_metric_helper_time (helper_boot_id, observed_at),
  KEY idx_browser_metric_retention (created_at),
  CONSTRAINT fk_browser_metric_local_agent_session
    FOREIGN KEY (local_agent_session_id) REFERENCES local_agent_session(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Append-only local helper browser observation samples; raw retention 14 days';
