CREATE TABLE presale_report_export (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '导出任务ID',
  report_id BIGINT NOT NULL COMMENT '售前报告ID',
  version_id BIGINT NOT NULL COMMENT '售前报告版本ID',
  idempotency_key VARCHAR(256) NOT NULL COMMENT '幂等键: reportId:versionId:editableContentHash:exportProfile',
  export_profile VARCHAR(64) NOT NULL DEFAULT 'PDF_A4_DPR2' COMMENT '导出配置档位',
  file_format VARCHAR(16) NOT NULL DEFAULT 'PDF' COMMENT '文件格式',
  status VARCHAR(32) NOT NULL COMMENT 'PENDING/RUNNING/SUCCESS/FAILED/CANCELED',
  error_msg VARCHAR(2000) NULL COMMENT '最近一次失败错误信息',
  retry_count INT NOT NULL DEFAULT 0 COMMENT '重试次数; retry 不改 idempotency_key,原行 FAILED 改回 PENDING 并 +1',
  cancel_requested TINYINT NOT NULL DEFAULT 0 COMMENT '取消请求标记;DB 是真理之源,内存 cancellationRegistry 仅辅助 RUNNING 收尾',
  worker_id VARCHAR(64) NULL COMMENT '抢占任务的 worker 标识: hostname + pid + uuid',
  file_key VARCHAR(512) NULL COMMENT 'PDF 文件对象存储 key',
  file_size BIGINT NULL COMMENT 'PDF 文件大小, bytes',
  file_pages INT NULL COMMENT 'PDF 页数',
  expire_at DATETIME NULL COMMENT 'PDF 文件和快照对象过期时间',
  snapshot_storage_type VARCHAR(32) NOT NULL DEFAULT 'INLINE' COMMENT 'INLINE/OBJECT;超过应用层阈值自动转 OBJECT',
  snapshot_json JSON NULL COMMENT 'INLINE 快照;应用层限制 <= 1MB',
  snapshot_key VARCHAR(512) NULL COMMENT 'OBJECT 快照 key: presale/exports/{export_id}/snapshot.json; 与 PDF 同 expire_at 清理',
  render_token_id VARCHAR(64) NULL COMMENT '当前渲染 token id;完整 token 存 Redis 并绑定任务超时 TTL',
  metrics_json JSON NULL COMMENT '渲染指标/debug摘要/retry_history',
  trigger_user_id BIGINT NOT NULL COMMENT '触发导出的用户ID',
  trigger_at DATETIME NOT NULL COMMENT '触发导出时间',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_idempotency_key (idempotency_key),
  KEY idx_trigger_user_status (trigger_user_id, status),
  KEY idx_report_version (report_id, version_id),
  KEY idx_status_updated_at (status, updated_at),
  KEY idx_expire_at (expire_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='售前报表PDF导出任务表';
