package com.huanjing.geo.module.content.service;

public record PromptContextRequest(Long projectId,
                                   String topicSource,
                                   String articleType,
                                   String channelGroupCode,
                                   String channelSubCode,
                                   String topic,
                                   String topicAsQuestion,
                                   String length,
                                   Long keywordGroupId,
                                   String keywordGroupName,
                                   String extraPrompt,
                                   Long promptTemplateId,
                                   Long promptTemplateVersionId,
                                   String perspectiveCode,
                                   String perspectiveMatchedScope,
                                   Long perspectiveMatchedConfigId,
                                   String medicalIndustryCode,
                                   String medicalCategoryCode,
                                   String medicalCategoryName,
                                   Long topicAngleId,
                                   String structureSkeleton,
                                   String focus,
                                   int articleIndexInBatch,
                                   String questionSceneCode) {
    public PromptContextRequest(Long projectId,
                                String topicSource,
                                String articleType,
                                String channelGroupCode,
                                String channelSubCode,
                                String topic,
                                String topicAsQuestion,
                                String length,
                                Long keywordGroupId,
                                String keywordGroupName,
                                String extraPrompt,
                                Long promptTemplateId,
                                Long promptTemplateVersionId,
                                String perspectiveCode,
                                String perspectiveMatchedScope,
                                Long perspectiveMatchedConfigId,
                                String medicalIndustryCode,
                                String medicalCategoryCode,
                                String medicalCategoryName,
                                Long topicAngleId,
                                String structureSkeleton,
                                String focus,
                                int articleIndexInBatch) {
        this(projectId, topicSource, articleType, channelGroupCode, channelSubCode, topic, topicAsQuestion, length,
                keywordGroupId, keywordGroupName, extraPrompt, promptTemplateId, promptTemplateVersionId,
                perspectiveCode, perspectiveMatchedScope, perspectiveMatchedConfigId,
                medicalIndustryCode, medicalCategoryCode, medicalCategoryName, topicAngleId, structureSkeleton, focus,
                articleIndexInBatch, null);
    }

    public PromptContextRequest(Long projectId,
                                String topicSource,
                                String articleType,
                                String channelGroupCode,
                                String channelSubCode,
                                String topic,
                                String topicAsQuestion,
                                String length,
                                Long keywordGroupId,
                                String keywordGroupName,
                                String extraPrompt,
                                Long promptTemplateId,
                                Long promptTemplateVersionId,
                                String perspectiveCode,
                                String perspectiveMatchedScope,
                                Long perspectiveMatchedConfigId,
                                int articleIndexInBatch) {
        this(projectId, topicSource, articleType, channelGroupCode, channelSubCode, topic, topicAsQuestion, length,
                keywordGroupId, keywordGroupName, extraPrompt, promptTemplateId, promptTemplateVersionId,
                perspectiveCode, perspectiveMatchedScope, perspectiveMatchedConfigId,
                null, null, null, null, null, null, articleIndexInBatch, null);
    }
}
